// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://akdllbzmlrlrfrxokymv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFrZGxsYnptbHJscmZyeG9reW12Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI5Njg1MjYsImV4cCI6MjA2ODU0NDUyNn0.1HH0yaSosDSjo9VXfZYRDStgwjM5aBZrjmm6GwnRQ0U";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});